### ISSUE TITLE
Duplicate sentry tickets when using SentryLogWriter + productionExceptionHandler

### ISSUE THREAD

**Issue by cweiske** [networkteam/sentry_client#100]
When following the README and configuring the `productionExceptionHandler` as well as the log `writerConfiguration`, exceptions are reported twice to Sentry.

One is reported by the  as "level: error"
```
TYPO3\CMS\Core\Error\Exception
PHP Warning: Undefined array key "category" in /var/www/typo3/...php line 71
```
stack trace:
1. TYPO3\CMS\Core\Error\ErrorHandler::handleError line 138
2. Sentry\ErrorHandler::handleError line 342
3. MyClass

the other one is "level: warning"
```
ErrorException
Warning: Undefined array key "category"
```

stack trace:
1. MyClass

---

The duplicate reports go away when I disable the log writer.

Now my questions:
- Is the log writer enough and the exception handler is not needed at all?
- If both should be used, how can I get rid of the duplicates?

----

This happens with TYPO3 12.4.13 and sentry_client 5.0.2.

My `config/system/additional.php` contains:
```
// Register exception handler                                    
$GLOBALS['TYPO3_CONF_VARS']['SYS']['productionExceptionHandler']
    = Networkteam\SentryClient\ProductionExceptionHandler::class;
// Forward log messages to Sentry                                
$GLOBALS['TYPO3_CONF_VARS']['LOG']['writerConfiguration'] = [
    \TYPO3\CMS\Core\Log\LogLevel::ERROR => [
        \Networkteam\SentryClient\SentryLogWriter::class => [],
    ],
];
```

**Comment by christophlehmann** [comment]
Log messages from Core ErrorHandler are excluded because Sentrys error Integrations are enabled.

I guess you have E_WARNING in `$GLOBALS['TYPO3_CONF_VARS']['SYS']['exceptionalErrors']` which turns warnings into Exceptions and thus reported again.

**Comment by christophlehmann** [comment]
Is this the case?

**Comment by cweiske** [comment]
I do indeed have `'exceptionalErrors' => 12290` which [translates](https://maximivanov.github.io/php-error-reporting-calculator/) to
```
E_WARNING | E_RECOVERABLE_ERROR | E_DEPRECATED
```

**Comment by cweiske** [comment]
The problem is gone when upgrading to 5.1.0.
Downgrading to 5.0.2 makes it appear again.
