### ISSUE TITLE
[FEATURE REQUEST] Support TYPO3 9

### ISSUE THREAD

**Issue by WebsiteDeveloper** [networkteam/sentry_client#15]
Hi we are currently working on switching to TYPO3 9 for new projects especially cause the new LTS version gets released tomorrow.
Would be nice to have this extension available :)

**Comment by derhansen** [comment]
The current version works fine with TYPO3 9.5. Composer dependencies and ext_emconf.php just need to be updated. See #17

**Comment by ger4003** [comment]
Release 2.0.2 is compatible with TYPO3 9.5 thanks to @derhansen
