### ISSUE TITLE
Cleanup ConfigurationService.php

### ISSUE THREAD

**Issue by christophlehmann** [networkteam/sentry_client#19]
Replace `unserialize($GLOBALS['TYPO3_CONF_VARS']['EXT']['extConf']['sentry_client']`

See https://docs.typo3.org/typo3cms/CoreApiReference/ExtensionArchitecture/ConfigurationOptions/Index.html#configuration-options

**Comment by ger4003** [comment]
Replace `$_EXTKEY` by `sentry_client` in `ext_localconf.php`.

See https://github.com/TYPO3/TYPO3.CMS/blob/d79b5b357bb3d89e0df74fdccb4faf2de24b69db/typo3/sysext/core/Documentation/Changelog/9.0/Important-82692-GuidelinesForExtensionFiles.rst
