### ISSUE TITLE
activatePageNotFoundHandlingActive has no effect

### ISSUE THREAD

**Issue by derhansen** [networkteam/sentry_client#21]
The extension setting `activatePageNotFoundHandlingActive` does not have any effect, since it is not being used in `ConfigurationService`- see: https://github.com/networkteam/sentry_client/blob/master/Classes/Service/ConfigurationService.php#L13

`pageNotFoundHandlingActive` vs. `activatePageNotFoundHandlingActive`

**Comment by christophlehmann** [comment]
Good catch! Is fixed.
