### ISSUE TITLE
Set real client IP from TYPO3 environment variables

### ISSUE THREAD

**Issue by abeutel** [networkteam/sentry_client#26]
Use GeneralUtility::getIndpEnv() to set the client remote address from TYPO3 system environment variables to resolve proper address on proxied requests.

**Comment by abeutel** [comment]
Hey @christophlehmann, is there any chance to get this patch merged soon? Would love to avoid Composer-patching the Sentry client in every installation ;-)

**Comment by christophlehmann** [comment]
Hey @abeutel Looks good. I will have a deeper look at it later this week and it will be fixed
