### ISSUE TITLE
Set sentry project environment by default

### ISSUE THREAD

**Issue by koehnlein** [networkteam/sentry_client#28]
First of all, thanks for your work and your extension! :-)

Since sentry provides environments for all projects, I think, it would be great to automatically use the TYPO3 application context name as environment name in sentry. Or are you leaving the environment empty intentionally and it is only me, setting the environment?

If you confirm, it would be a good idea, to set sentrys environment to TYPO3's application context name, I could offer a tiny merge request.

**Comment by christophlehmann** [comment]
Hey Albrecht,

Good point! Next release is coming soon
