### ISSUE TITLE
Replace deprecated raven-php by sentry-php

### ISSUE THREAD

**Issue by bittner** [networkteam/sentry_client#3]
This extension [ships raven-php](https://github.com/networkteam/sentry_client/tree/master/vendor) as a Git submodule.

As of its repository README [raven-php is now deprecated](https://github.com/getsentry/raven-php) and should be replaced by [sentry-php](https://github.com/getsentry/sentry-php).

**Comment by bittner** [comment]
This issue is covered by PR #2.

Any plans to merge it anytime soon?

**Comment by christophlehmann** [comment]
I added composer support. Packagist registration follows tomorrow
