### ISSUE TITLE
"Uncaught" TYPO3 errors

### ISSUE THREAD

**Issue by agendartobias** [networkteam/sentry_client#30]
Hey, in TYPO3 i get errors like this:

`Core: Exception handler (WEB): Uncaught TYPO3 Exception: Call to a member function getRecurrence() on null | Error thrown in file /var/www/typo3/www.mysite.si/typo3conf/ext/dated_news/Classes/Controller/NewsController.php in line 624. Requested URL: https://www.mysite.si/subpage1/subpage2...../`

But sentry dont recognize them. Is there a problem in my configuration?

**Comment by christophlehmann** [comment]
Hey, can you provide some more infos?

* TYPO3 Version
* sentry_client version
* configuration ($GLOBALS['TYPO3_CONF_VARS']['SYS'])

**Comment by agendartobias** [comment]
Hey,

TYPO3 9.5.13,
sentry_client 3.0.0
Configuration
![Zajeta slika](https://user-images.githubusercontent.com/28923508/74920893-2c02bf00-53cd-11ea-9f6d-fdb3f084b072.JPG)

And some additional configuration:

`$GLOBALS['TYPO3_CONF_VARS']['LOG']['TYPO3']['CMS']['deprecations']['writerConfiguration'][\TYPO3\CMS\Core\Log\LogLevel::NOTICE] = [];
$GLOBALS['TYPO3_CONF_VARS']['LOG']['writerConfiguration'] = array(
    \TYPO3\CMS\Core\Log\LogLevel::ERROR => array(
      'TYPO3\\CMS\\Core\\Log\\Writer\\FileWriter' => array(
        'logFile' => 'typo3temp/var/log/typo3_7ac500bce5.log'
      )
    )
  );`

**Comment by christophlehmann** [comment]
Does it work in general?

Can you post your parsed configuration? (BE Configuration module)

`$GLOBALS['TYPO3_CONF_VARS']['EXTENSIONS']['sentry_client']` and `$GLOBALS['TYPO3_CONF_VARS']['SYS']`

To debug it you can add `die('here');` after https://github.com/networkteam/sentry_client/blob/master/Classes/Client.php#L21 to see where it stops

**Comment by agendartobias** [comment]
Hey, sorry it was actually problem in my Localconfiguration.php file, i had some custom configuration in it that broke everything defined bellow.

Anyway here is my configuration:

`sentry_client
activatePageNotFoundHandling = 1
dsn = https://62d08205253442e5b60741dbae591fff@sentry.io/2626697
messageBlacklistRegex =
release =
reportDatabaseConnectionErrors = 0
reportUserInformation = userid
showEventId = 1`

**Comment by christophlehmann** [comment]
Okay, you are welcome!
