### ISSUE TITLE
Support JavaScript error reporting

### ISSUE THREAD

**Issue by markuspoerschke** [networkteam/sentry_client#33]
Sentry can also be used to [report error on web pages using JavaScript](https://docs.sentry.io/platforms/javascript/).

This can normally be done by adding a HTML snippet or by bundling the JavaScript-file with the JavaScript sources. In both cases, the sentry configuration can be provided by adding `window.SENTRY_...` variables.

Since these information are available already, I think it is a good idea to extend this extension to output the values to the frontend. The frontend part will be active only, if the TypoScript template is included. Therefore this feature will become "optional" to use.

The acceptance criteria for including the JavaScript SDK in this extension are the following:

1. The JavaScript will be included and configured if the TypoScript setup of this extension is included in the site package’s template.
2. The Sentry JavaScript SDK is loaded either from:
2.a. CDN by Sentry
2.b. a copy in this Extension
2.b. disabled, because it is bundled with the JavaScript from the project.
3. Sentry is initialized either:
3.a. automatically, because the extension adds the `Sentry.init()` call
3.b. by the projects JavaScript (no `Sentry.init()` is added)

Do you think that it makes sense to add this feature to this extension? In that case I can check if I can work on a Merge Request.

**Comment by cweiske** [comment]
The extension https://extensions.typo3.org/extension/sentry_client_js  does this.

**Comment by christophlehmann** [comment]
I would not add that functionality to the extension. I think the best approach to do it is to integrate it in your frontend workflow (webpack or similar). The `dsn` from extConf can pretty easily injected in the DOM with TypoScripts `getText`.

**Comment by amenk** [comment]
> The extension https://extensions.typo3.org/extension/sentry_client_js does this.

Unfortunately the extension is no longer maintained: https://github.com/AOEpeople/TYPO3-sentry-client-js
