### ISSUE TITLE
Consider adding a workaround for GitLab's sentry-payload error collector

### ISSUE THREAD

**Issue by LeoniePhiline** [networkteam/sentry_client#54]
See https://gitlab.com/gitlab-org/gitlab/-/issues/340178#note_845578316

GitLab is able to collect sentry payload, but fails if `$_SERVER['PATH_INFO']` is an empty string.

The debug and production error handlers could set (and optionally reset afterwards) the following:

```php
if ($_SERVER['PATH_INFO'] === '') {
    $_SERVER['PATH_INFO'] = null;
}
```

This fixes an `Validation failed: Actor can't be blank` response caused by an empty `"transaction"` key in the sentry JSON payload.

**Comment by christophlehmann** [comment]
Hi @LeoniePhiline,

i think this is not the best place for the fix. It should better be fixed upstream in https://github.com/getsentry/sentry-php or in gitlab.
