### ISSUE TITLE
Change sentry/sentry version to 1.8.3

### ISSUE THREAD

**Issue by r0bin** [networkteam/sentry_client#6]
Hello there,

are there any plans to push the version used for the [**sentry/sentry** dependency](https://packagist.org/packages/sentry/sentry) to something like the most up-to-date 1.8.3?

Currently this extension uses 0.10 which is from 2014 ...

I smell a scent of #nevertoucharunningsystem 🤔

**Comment by christophlehmann** [comment]
I created a branch for you: newest-sentry-client

i) Would you check it?
ii) Are there any Features missing in the older version?

**Comment by metaa** [comment]
Ah yeah, thanks for that so far.
I don't have a TYPO3 v8 instance at hand right now, but I'll try it out later today.

**Comment by RobinScholz** [comment]
Ah yeah, thanks for that so far.
I don't have a TYPO3 v8 instance at hand right now, but I'll try it out later today.
