### ISSUE TITLE
Add support for PSR-3 variable interpolation in logger

### ISSUE THREAD

**Issue by sascha-egerer** [networkteam/sentry_client#66]
In TYPO3 11 the logging has been adjusted to support variable interpolation in log messages as defined in PSR-3.  https://www.php-fig.org/psr/psr-3/

The interpolation must be called in the log writer.

**Comment by christophlehmann** [comment]
Thanks for the PR. 👍 

On merge lets also check the message grouping by fingerprint with non-interpolated messages. Might be better then the stackstrace.
