### ISSUE TITLE
SYS ObjectOverride overrides TYPO3 ProductionExceptionhandler by default

### ISSUE THREAD

**Issue by Tuurlijk** [networkteam/sentry_client#68]
Why is this done? Does this not enable the sentry ProductionExceptionHandler by default?

https://github.com/networkteam/sentry_client/blob/8bf5825b9e61668c33bd969f22e109f7ae8fd896/ext_localconf.php#L12

**Comment by christophlehmann** [comment]
>Why is this done?

We want to catch Exceptions that occur in content rendering too. 

>Does this not enable the sentry ProductionExceptionHandler by default?

Yes, that's true and basically fine for us.

If one would improve it:

In development context it might be better to see the exception message directly instead of reporting it to Sentry. A PR is welcome.

**Comment by Tuurlijk** [comment]
Hi,

I'll do a pull request.

Exception handling for content elements can be set in TypoScript: https://github.com/Tuurlijk/t3ext-bugsnag/#exceptions-thrown-by-content-elements

**Comment by christophlehmann** [comment]
Completed via #76
