### ISSUE TITLE
php-http/discovery modifies composer.json

### ISSUE THREAD

**Issue by steffenf14** [networkteam/sentry_client#77]
php-http/discovery upgraded to version 1.15.0 and brings a new feature that modifies your existing composer.json. I consider this very harmful, please consider to remove this package.

Also 1.15.0 is broken and loops endlessly. https://github.com/php-http/discovery/issues/213

**Comment by christophlehmann** [comment]
It's not a direct dependency.

**Comment by jpmschuler** [comment]
I agree with both, current hotfix for project root `composer.json`
```
"conflict": {
   "php-http/discovery": "1.15.0"
},
```
seems the best solution for the situation, while still allowing to not block future repairs. And allowing to update `sentry/sentry` to `^3.13.0`

**Comment by christophlehmann** [comment]
Is fixed [upstream](https://github.com/getsentry/sentry-php/releases/tag/3.13.1)
