### ISSUE TITLE
Deprecation of DebugExceptionHandler - alternatives?

### ISSUE THREAD

**Issue by cweiske** [networkteam/sentry_client#79]
The README's changelog says:

> 4.2.0
> Deprecated: Usage of DebugExceptionHandler

(this came with 2e34725f89cf59a55e794e35adc655dd106e46ff, but no further explanation)

In #76 you remove the debugexceptionhandler class, but the commit also does not tell what the alternative is.

How can we get exceptions into sentry on testing and staging systems, while at the same time see the full exception trace when an error occurs?

**Comment by christophlehmann** [comment]
That was not ver Semver, sorry for that! Nevermind someone uses the class... We don't use it since a half decade.

>How can we get exceptions into sentry on testing and staging systems, while at the same time see the full exception trace when an error occurs?

The ProductionExceptionHandler normally shows an EventId, which you can paste into the Issue search field in Sentry. Is that a way for you?

**Comment by cweiske** [comment]
This is indeed a way, but it takes two more steps when debugging issues :(

**Comment by christophlehmann** [comment]
Will keep the DebugExceptionHandler.
