### ISSUE TITLE
Use `sentry/sentry` instead of `sentry/sdk`

### ISSUE THREAD

**Issue by derhansen** [networkteam/sentry_client#82]
`sentry/sdk` bundles an own  HTTP client (`symfony/http-client`), which however is superfluous, since TYPO3 bundles a HTTP client too (`guzzle/guzzle`).

I therefore suggest to use `sentry/sentry`, which uses `php-http/discover` to discover any HTTP clients used by depending packages. For TYPO3, the `php-http/guzzle7-adapter` will be added to `composer.json` by the plugin.

**Comment by christophlehmann** [comment]
Thank you!
