### ISSUE TITLE
Exception if extension not fully configured

### ISSUE THREAD

**Issue by georgringer** [networkteam/sentry_client#92]
If extension is just installed but no settings set, the following exception is thrown

```
Networkteam\SentryClient\Service\ConfigurationService::getReportUserInformation(): Return value must be of type string, null returned
```

reason is

```php
public static function getReportUserInformation(): string
    {
        return self::getExtensionConfiguration(self::REPORT_USER_INFORMATION);
    }
```

suggestion: add additional ` ?? ''`

**Comment by christophlehmann** [comment]
As of `ext_conf_template.txt` the default is `userid`. Since there are only 2 possible values left, the return type could also be a bool:  string `none`/empty/unset => false, else true. A PR is welcome.
