### ISSUE TITLE
Testing code does not work

### ISSUE THREAD

**Issue by georgringer** [networkteam/sentry_client#93]
the proposed testing code in readme does not work
```
page.20 = USER
page.20 {
    userFunc = Networkteam\SentryClient\Client->captureException
}
``` 

as it throws an exception:

```
TypeError
Networkteam\SentryClient\Client::captureException(): Argument #1 ($exception) must be of type Throwable, string given, called in /var/www/html/app/site/vendor/typo3/cms-frontend/Classes/ContentObject/ContentObjectRenderer.php on line 4752
```

a possible implementation to test could be

```php
    public static function captureTestException(): ?EventId
    {
        $exception = new \Exception('Test exception');
        return captureException($exception);
    }
```

**Comment by christophlehmann** [comment]
This TypeError is reported to Sentry. 

If that is not the case, did you set the Sentry DSN and configured an ExceptionHandler (Dev context => DebugExceptionHandler, Prod => ProductionExceptionHandler) ?

**Comment by robsonrobi** [comment]
I have exactly the same error, and yes, i set the ProductionExceptionHandler as explained.

**Comment by christophlehmann** [comment]
When you visit the frontend, do you see a stacktrace?

**Comment by cweiske** [comment]
I did not get the exception reported locally when I only set the production exception handler. Configuring the `debugExceptionHandler` helped, just as christophlehmann described.
