### ISSUE TITLE
Missing support for Sentry Web Vitals

### ISSUE THREAD

**Issue by alexanderschnitzler** [networkteam/sentry_client#97]
Hi folks,

in order to allow profiling, the configuration option `traces_sample_rate` needs to be set which is currently not possible as the set of options is controlled by this package. See https://docs.sentry.io/platforms/php/performance/ for reference.

It would be nice if the package supported either adding arbitrary configuration or the full set of options sentry offers. Especially this option should be easy to pass through via `EXTCONF`.

Greetings,
Alex

**Comment by christophlehmann** [comment]
Hi Alex,

it's possible, see Readme:

`$GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['sentry_client']['options']['server_name'] = 'web3';`

**Comment by alexanderschnitzler** [comment]
Hi Christoph,

my bad, I totally missed that yesterday when I quickly browsed the code. Found this in a couple of seconds now:

```php
if (is_array($extConf['options'] ?? null)) {
    $options = array_merge($options, $extConf['options']);
}
if (is_callable($extConf['modifyOptions'] ?? null)) {
    $options = call_user_func($extConf['modifyOptions'], $options);
}
```

Thanks!
